#!/bin/bash
# Generated by roach.slurm.submit() -- piped to sbatch on stdin, so slurm keeps its
# own copy and nothing has to live on shared storage. Placeholders are filled in
# by submit(); everything here is deliberately the same for every job.
set -euo pipefail

echo "=== $(date -Is) job $SLURM_JOB_ID on $(hostname), restarts=${SLURM_RESTART_COUNT:-0} ==="
echo "name=@NAME@ repo=@REPO@ commit=@COMMIT@ branch=@BRANCH@ run_id=@RUN_ID@ target=@TARGET@"

export USER=${USER:-$(id -un)}
export TMPDIR=/tmp/$USER
mkdir -p "@CLONE_ROOT@"

# Node-local home, caches and tokens; sets the node up if it has never been
# used. Spliced in rather than sourced from a path: this runs before the
# environment exists, so roach is not importable yet, and inlining also pins the
# node setup to the submission instead of to whatever is installed later. It
# comes before the clones so they get the job's HOME, PATH, caches and token.
@ENV@

# --------------------------------------------------------------------------- #
# Clones are keyed by commit and shared by every job at that commit on the node.
#
# A per-job clone threw away everything it built. That cost more than the disk:
# pixi keys its environments on the project path (a detached environment is
# literally NAME-HASH_OF_PATH), uv keys built wheels on the mtime of
# pyproject.toml, and cargo's artifacts live under the manifest. A clone at a
# fresh mktemp path therefore missed every one of those caches by construction,
# so each job re-solved the environment and recompiled the extensions -- minutes
# of a full allocation, per job, for a result the previous job had already
# produced byte for byte.
#
# The first job at a key on a node pays that once and the rest pay a lock
# acquisition. What the key is -- the commit or the branch -- is the submitter's
# `clone_by`, and it is the one real choice here:
#
#   commit: a clone is exactly one commit, forever. A queued job cannot change
#           under you, and every new commit pays for its own environment.
#   branch: one clone, moved to each submitted commit. The environment, the
#           cargo target dir and everything else built here survive to the next
#           commit -- and a later submission moves the checkout under a job that
#           is still running from it.
#
# The key is also what the clone is checked out at, which is the whole of the
# difference: a commit clone is pinned to the sha that was submitted, a branch
# clone follows the branch and is brought to its tip every time a job arrives.
# So a branch job runs what the branch says now, which may be newer than the
# commit it was submitted from -- that is the point of it, and the reason it is
# for iterating rather than for a sweep you will read later.
# --------------------------------------------------------------------------- #
REPO_DIR=@CLONE_ROOT@/repo-@CLONE_KEY@

# One place that knows how to reach a private repo, used to clone and to fetch.
git_auth() {  # <git args...>
    git -c url."https://x-access-token:$(tr -d '[:space:]' < "@SECRETS_DIR@/github")@github.com/".insteadOf="https://github.com/" \
        "$@"
}

# What this clone is supposed to be at: a fixed sha, or wherever the branch has
# got to. The branch case is resolved fresh on every job, which is how a branch
# clone picks up commits pushed since the job was submitted.
want_ref() {  # <dir> -> sha
    if [[ @CLONE_BY@ == branch ]]; then
        ( cd "$1" && git_auth fetch --quiet origin @BRANCH@ )
        git -C "$1" rev-parse FETCH_HEAD
    else
        echo @COMMIT@
    fi
}

git_clone() {  # <url> <dir>
    git_auth clone --quiet "$1" "$2"
}

# Bring the clone to what it should be at. Returns 0 if it moved, so the caller
# knows to build again; 1 if it was already there, which is every job after the
# first at a commit, and every job at all in commit mode.
sync_to_ref() {  # <dir>
    local dir=$1 want head
    want=$(want_ref "$dir")
    head=$(git -C "$dir" rev-parse HEAD 2>/dev/null || echo none)
    if [[ $head == "$want" ]]; then return 1; fi
    if [[ $head != none ]]; then
        echo "clone: moving $dir from ${head:0:7} to ${want:0:7}"
    fi
    git -C "$dir" checkout --quiet --force "$want"
    return 0
}

# A clone is per commit, so iterating -- which is a commit per attempt -- pays
# for a new one every time. Nothing about that is wrong; what was wrong is
# re-solving the environment for a commit that did not touch a dependency, which
# was minutes. The steps below print what they cost, because a regression here
# is invisible otherwise. Measured on this project, per new commit: git clone
# ~3s, pixi install ~50s, build ~7s -- against ~9 minutes before the lock was
# seeded. The install is what remains, and it is pixi materializing an 8.5 GiB
# environment because the environment is keyed on the clone's path.
seed_lock() {  # in the new clone, before pixi install
    # pixi.lock is gitignored, so a fresh clone has none and pixi solves from
    # scratch -- the same solve, per commit, for a commit that did not touch a
    # dependency. Copy the newest lock from a ready clone whose manifest is
    # byte-identical; pixi validates it against the manifest anyway and re-solves
    # if it disagrees, so a stale lock costs nothing and a matching one skips
    # the solve entirely.
    # A branch-keyed clone that moved to a new commit already has the lock it
    # solved for the last one, and pixi will re-solve it if the manifest moved
    # too. Leave it alone -- and never seed from ourselves, which is what a
    # ready clone in this loop would otherwise be.
    if [[ -f pixi.lock ]]; then return 0; fi
    local newest= d
    for d in "@CLONE_ROOT@"/*/; do
        [[ -f $d/.roach-ready && -f $d/pixi.lock ]] || continue
        cmp -s pyproject.toml "$d/pyproject.toml" || continue
        if [[ -z $newest || $d/pixi.lock -nt $newest ]]; then newest=$d/pixi.lock; fi
    done
    if [[ -n $newest ]]; then
        cp "$newest" pixi.lock
        echo "prepare: seeded pixi.lock from $newest"
    fi
}

prepare_repo() {
    local t
    t=$SECONDS; seed_lock; echo "prepare: seed_lock $((SECONDS - t))s"
    # The lock (seeded or solved here) lives in the clone, so every later job at
    # this commit inherits it.
    t=$SECONDS; pixi install; echo "prepare: pixi install $((SECONDS - t))s"
    t=$SECONDS
    # Whatever this project needs built before its ranks start: the submitter's
    # `setup` argument, one command per line, empty is fine. Naming the
    # placeholder in this comment would splice the commands into it, and every
    # line after the first would break out and run as garbage.
    @SETUP@
    echo "prepare: setup $((SECONDS - t))s"
}

# Whoever takes the lock builds; .roach-ready, written last, is what publishes
# the result. A builder killed mid-flight drops the lock (flock releases when
# the fd closes) and leaves an unmarked directory, which the next holder wipes.
# Late arrivals block here for the one build, then find the marker and fall
# straight through.
#
# Nothing here ever deletes a clone. They are cheap (an environment is reflinked
# from the package cache: ~230 MiB of its 8 GiB is its own) and deleting one is
# `rm -rf` when a disk actually fills up -- which is a person's call, not a
# rule a job should be enforcing at 3am against a directory somebody is using.
#
# Built in place, not staged and renamed: the environment is keyed to the path
# it was installed at, so moving the project afterwards makes pixi reinstall the
# editable path dependency -- for a maturin project, a full recompile, done by
# every rank at once, colliding in uv's shared build cache. Atomicity is the
# marker's job; the directory itself never moves.
clone_at_commit() {  # <dir> <url> <prepare-fn>
    local dir=$1 url=$2 prepare=$3
    exec 9>"$dir.lock"
    flock 9
    if [[ ! -f $dir/.roach-ready ]]; then
        echo "preparing $dir"
        rm -rf "$dir"
        local t=$SECONDS
        git_clone "$url" "$dir"
        sync_to_ref "$dir" || true
        echo "prepare: git clone $((SECONDS - t))s"
        ( cd "$dir" && "$prepare" )
        touch "$dir/.roach-ready"
    elif sync_to_ref "$dir"; then
        # The code changed under a clone that is already built, so build again:
        # the environment is keyed on this path and survives, and everything
        # that did not change is a cache hit rather than work.
        ( cd "$dir" && "$prepare" )
        touch "$dir/.roach-ready"
    fi
    exec 9>&-
    echo "clone: $dir @ $(git -C "$dir" rev-parse --short HEAD)"
}

clone_at_commit "$REPO_DIR" "@REPO@" prepare_repo

cd "$REPO_DIR"
# What this run's environment actually was, next to its logs. A record, not a
# cache: the clone holds the lock the jobs share.
cp pixi.lock "@LOG_ROOT@/@RUN_ID@.pixi.lock"

# One task per GPU: each rank is a slurm task, so slurm's preemption SIGTERM
# reaches every rank directly. They save resume.pt at the next step boundary and
# exit; this script only has to outlive them, hence the ignored trap. Slurm
# requeues the job itself, and the run id is fixed, so the next attempt resumes.
trap '' TERM USR1
# srun refuses to start when SLURM_CPUS_PER_TASK disagrees with the allocation's
# SLURM_TRES_PER_TASK ("cpus-per-task set by two different environment
# variables"), and a stale value reaches a job easily enough -- a submitting
# shell that is itself inside an allocation is one way. The allocation is the
# authority, so drop the environment's opinion and let srun read it.
unset SLURM_CPUS_PER_TASK
# --export=ALL here is not the same as sbatch's: that one kept the *submit
# shell* out of the job, this one lets the tasks inherit the environment this
# script just built. Without it srun starts them nearly empty (--export=NONE
# sets SLURM_EXPORT_ENV=NONE) and they find neither pixi nor the tokens, caches
# and node-local HOME that env.sh set up.
#
# --frozen: the clone is shared, so a rank that re-solved would rewrite
# pixi.lock underneath every other job at this commit. The lock is the one
# prepare_repo wrote; use it. Installing is deliberately still allowed -- a rank
# that finds the environment wrong should say so, or fix it, rather than run on
# in whatever state it was left in.
#
# The srun line itself is filled in by submit(): a batch job starts its ranks in
# its own allocation, an overlapping job starts them as a sibling step of an
# allocation somebody else is holding. Everything above this point is identical
# either way.
@LAUNCH@ &
wait $!
