#!/bin/bash
# Generated by roach.slurm.submit() -- piped to sbatch on stdin, so slurm keeps its
# own copy and nothing has to live on shared storage. Placeholders are filled in
# by submit(); everything here is deliberately the same for every job.
set -euo pipefail

echo "=== $(date -Is) job $SLURM_JOB_ID on $(hostname), restarts=${SLURM_RESTART_COUNT:-0} ==="
echo "name=@NAME@ repo=@REPO@ commit=@COMMIT@ run_id=@RUN_ID@ target=@TARGET@"

export USER=${USER:-$(id -un)}
export TMPDIR=/tmp/$USER
mkdir -p "@CLONE_ROOT@"

# Node-local home, caches and tokens; sets the node up if it has never been
# used. Spliced in rather than sourced from a path: this runs before the
# environment exists, so roach is not importable yet, and inlining also pins the
# node setup to the submission instead of to whatever is installed later. It
# comes before the clones so they get the job's HOME, PATH, caches and token.
@ENV@

# --------------------------------------------------------------------------- #
# Clones are keyed by commit and shared by every job at that commit on the node.
#
# A per-job clone threw away everything it built. That cost more than the disk:
# pixi keys its environments on the project path (a detached environment is
# literally NAME-HASH_OF_PATH), uv keys built wheels on the mtime of
# pyproject.toml, and cargo's artifacts live under the manifest. A clone at a
# fresh mktemp path therefore missed every one of those caches by construction,
# so each job re-solved the environment and recompiled the extensions -- minutes
# of a full allocation, per job, for a result the previous job had already
# produced byte for byte.
#
# Keyed by commit, the first job on a node pays that once and the rest pay a
# lock acquisition. Reproducibility is unchanged: a clone is still exactly the
# submitted commit, and a different commit is a different directory, so a queued
# job still cannot change under you.
# --------------------------------------------------------------------------- #
REPO_DIR=@CLONE_ROOT@/repo-@COMMIT@

git_clone() {  # <url> <commit> <dir>
    git -c url."https://x-access-token:$(tr -d '[:space:]' < "@SECRETS_DIR@/github")@github.com/".insteadOf="https://github.com/" \
        clone --quiet "$1" "$3"
    git -C "$3" checkout --quiet "$2"
}

# A clone is per commit, so iterating -- which is a commit per attempt -- pays
# for a new one every time. Nothing about that is wrong; what was wrong is
# paying for work the previous commit already did. Each of these seeds the new
# clone from the node's caches, and each reports what it cost, because a
# regression here is minutes per attempt and otherwise invisible.
seed_lock() {  # in the new clone, before pixi install
    # pixi.lock is gitignored, so a fresh clone has none and pixi solves from
    # scratch -- the same solve, per commit, for a commit that did not touch a
    # dependency. Copy the newest lock from a ready clone whose manifest is
    # byte-identical; pixi validates it against the manifest anyway and re-solves
    # if it disagrees, so a stale lock costs nothing and a matching one skips
    # the solve entirely.
    local newest= d
    for d in "@CLONE_ROOT@"/*/; do
        [[ -f $d/.roach-ready && -f $d/pixi.lock ]] || continue
        cmp -s pyproject.toml "$d/pyproject.toml" || continue
        if [[ -z $newest || $d/pixi.lock -nt $newest ]]; then newest=$d/pixi.lock; fi
    done
    if [[ -n $newest ]]; then
        cp "$newest" pixi.lock
        echo "prepare: seeded pixi.lock from $newest"
    fi
}

env_prefix() {  # <dir> -- where pixi keeps that project's environment, or nothing
    # Never fails: this is an optimization, and `set -e` would turn "pixi cannot
    # say" into a dead job rather than a slow one.
    local out
    out=$( (cd "$1" && pixi info --json) 2>/dev/null ) || return 0
    printf '%s' "$out" | grep -o '"prefix": *"[^"]*"' | head -1 | cut -d'"' -f4 ||
        return 0
}

seed_env() {
    # The environment is the expensive part, and pixi keys it on the *project
    # path*: detached-environments puts it in the cache under a hash of that
    # path, so a per-commit clone means a per-commit environment -- 8.5 GiB
    # materialized and ~50s paid, for a commit that changed one python file.
    # (Measured: 33 environments for 5 live clones.)
    #
    # Hardlink one from a clone with a byte-identical lock instead. Same package
    # cache, same files, seconds instead of a minute. `pixi install` still runs
    # afterwards and reconciles what it finds, so a copy that is wrong in any
    # way is repaired rather than trusted -- and the editable install of *this*
    # clone is rewritten by the build in `setup`, which is what points the
    # environment at this commit's code.
    local dst src d
    dst=$(env_prefix .)
    [[ -n $dst && ! -e $dst ]] || return 0
    for d in "@CLONE_ROOT@"/*/; do
        [[ -f $d/.roach-ready ]] || continue
        cmp -s pixi.lock "$d/pixi.lock" || continue
        src=$(env_prefix "$d")
        [[ -n $src && -d $src ]] || continue
        mkdir -p "$(dirname "$dst")"
        if cp -al "$src" "$dst" 2>/dev/null; then
            echo "prepare: hardlinked env from $src"
        else
            # different filesystem, or a partial copy: leave nothing behind for
            # pixi to reconcile against
            rm -rf "$dst"
        fi
        return 0
    done
}

prepare_repo() {
    local t
    t=$SECONDS; seed_lock; echo "prepare: seed_lock $((SECONDS - t))s"
    t=$SECONDS; seed_env; echo "prepare: seed_env $((SECONDS - t))s"
    # The lock (seeded or solved here) lives in the clone, so every later job at
    # this commit inherits it.
    t=$SECONDS; pixi install; echo "prepare: pixi install $((SECONDS - t))s"
    t=$SECONDS
    # Whatever this project needs built before its ranks start: the submitter's
    # `setup` argument, one command per line, empty is fine. Naming the
    # placeholder in this comment would splice the commands into it, and every
    # line after the first would break out and run as garbage.
    @SETUP@
    echo "prepare: setup $((SECONDS - t))s"
    # An environment seeded from another clone starts out pointing at *that*
    # clone's code, and the build in `setup` is what re-points it here. If that
    # ever stops being true, the job would run a different commit than the one
    # it reports -- silently, and forever after for every job at this commit,
    # since the clone gets published either way. So prove it, and refuse to
    # publish a clone that cannot.
    local imported
    imported=$(pixi run --frozen python -c "import rt; print(rt.__file__)")
    case $imported in
        "$PWD"/*) echo "prepare: imports rt from this clone" ;;
        *) echo "prepare: FATAL rt resolves to $imported, not $PWD" >&2; exit 1 ;;
    esac
}

# Whoever takes the lock builds; .roach-ready, written last, is what publishes
# the result. A builder killed mid-flight drops the lock (flock releases when
# the fd closes) and leaves an unmarked directory, which the next holder wipes.
# Late arrivals block here for the one build, then find the marker and fall
# straight through.
#
# Built in place, not staged and renamed: the environment is keyed to the path
# it was installed at, so moving the project afterwards makes pixi reinstall the
# editable path dependency -- for a maturin project, a full recompile, done by
# every rank at once, colliding in uv's shared build cache. Atomicity is the
# marker's job; the directory itself never moves.
clone_at_commit() {  # <dir> <url> <commit> <prepare-fn>
    local dir=$1 url=$2 commit=$3 prepare=$4
    exec 9>"$dir.lock"
    flock 9
    if [[ ! -f $dir/.roach-ready ]]; then
        echo "preparing $dir"
        rm -rf "$dir"
        local t=$SECONDS
        git_clone "$url" "$commit" "$dir"
        echo "prepare: git clone $((SECONDS - t))s"
        ( cd "$dir" && "$prepare" )
        touch "$dir/.roach-ready"
    fi
    # Claim it before dropping the lock, so the reaper -- which takes the same
    # lock -- cannot see an unused clone that a job is in the middle of adopting.
    mkdir -p "$dir/.roach-inuse"
    touch "$dir/.roach-inuse/$SLURM_JOB_ID" "$dir/.roach-used"
    exec 9>&-
    echo "clone: $dir @ $(git -C "$dir" rev-parse --short HEAD)"
}

# Nothing deletes a clone when a job ends any more -- it is shared, and the next
# job at that commit wants it. Sweep instead: a clone goes once no live job
# holds it and nothing has touched it for the submitter's clone_ttl_days.
# Skipped entirely if squeue cannot answer, since "no live jobs" would then
# delete the world.
reap_clones() {
    local ttl=@CLONE_TTL_DAYS@ dir marker id
    if ! squeue -h -u "$USER" -o %i >/dev/null 2>&1; then
        echo "reap: squeue unavailable, skipping"
        return 0
    fi
    for dir in "@CLONE_ROOT@"/*/; do
        dir=${dir%/}
        if [[ $dir == "$REPO_DIR" ]]; then continue; fi
        if [[ ! -f $dir/.roach-ready ]]; then continue; fi
        # A job holding the lock is preparing or adopting this clone.
        exec 8>"$dir.lock"
        if ! flock -n 8; then exec 8>&-; continue; fi
        for marker in "$dir"/.roach-inuse/*; do
            if [[ ! -e $marker ]]; then continue; fi
            id=$(basename "$marker")
            if [[ -z $(squeue -h -j "$id" -o %i 2>/dev/null) ]]; then rm -f "$marker"; fi
        done
        if [[ -n $(ls -A "$dir/.roach-inuse" 2>/dev/null) ]]; then exec 8>&-; continue; fi
        if [[ -z $(find "$dir/.roach-used" -mtime "+$ttl" 2>/dev/null) ]]; then
            exec 8>&-; continue
        fi
        echo "reaping $dir (unused for >${ttl}d)"
        rm -rf "$dir"
        exec 8>&-
        rm -f "$dir.lock"
    done
}

clone_at_commit "$REPO_DIR" "@REPO@" "@COMMIT@" prepare_repo
reap_clones

# Release the claim when this job ends, so the reaper can retire the clone once
# the last job at this commit is done with it.
trap 'rm -f "$REPO_DIR/.roach-inuse/$SLURM_JOB_ID"' EXIT

cd "$REPO_DIR"
# What this run's environment actually was, next to its logs. A record, not a
# cache: the clone holds the lock the jobs share.
cp pixi.lock "@LOG_ROOT@/@RUN_ID@.pixi.lock"

# One task per GPU: each rank is a slurm task, so slurm's preemption SIGTERM
# reaches every rank directly. They save resume.pt at the next step boundary and
# exit; this script only has to outlive them, hence the ignored trap. Slurm
# requeues the job itself, and the run id is fixed, so the next attempt resumes.
trap '' TERM USR1
# srun refuses to start when SLURM_CPUS_PER_TASK disagrees with the allocation's
# SLURM_TRES_PER_TASK ("cpus-per-task set by two different environment
# variables"), and a stale value reaches a job easily enough -- a submitting
# shell that is itself inside an allocation is one way. The allocation is the
# authority, so drop the environment's opinion and let srun read it.
unset SLURM_CPUS_PER_TASK
# --export=ALL here is not the same as sbatch's: that one kept the *submit
# shell* out of the job, this one lets the tasks inherit the environment this
# script just built. Without it srun starts them nearly empty (--export=NONE
# sets SLURM_EXPORT_ENV=NONE) and they find neither pixi nor the tokens, caches
# and node-local HOME that env.sh set up.
#
# --frozen: the clone is shared, so a rank that re-solved would rewrite
# pixi.lock underneath every other job at this commit. The lock is the one
# prepare_repo wrote; use it. Installing is deliberately still allowed -- a rank
# that finds the environment wrong should say so, or fix it, rather than run on
# in whatever state it was left in.
#
# The srun line itself is filled in by submit(): a batch job starts its ranks in
# its own allocation, an overlapping job starts them as a sibling step of an
# allocation somebody else is holding. Everything above this point is identical
# either way.
@LAUNCH@ &
wait $!
