"""Submit the pretraining run. See [README.md](README.md)."""

from pathlib import Path

from roach.slurm.clusters import marlowe

from roach.slurm import submit

# 2026-08-22: one 8xH100 node on Marlowe's batch partition (--exclusive,
# 1456000M), the first real run there, on the cutoff subset that is on Marlowe
# scratch. Each rank is confined to its cpus_per_task cores (task/cgroup).
resources = marlowe.H100

tokens_per_gpu = 2**17  # H100-80G, the A100-80G's value
num_workers = resources.cpus_per_task  # train and eval loaders alike

submit(
    "rt.train:main",
    args=dict(
        embedder="all-MiniLM-L12-v2",
        d_text=384,
        num_blocks=12,
        d_model=512,
        num_heads=8,
        d_ff=2048,
        compile=True,
        materialize_attn_masks=True,
        loss_fn="huber",
        load_ckpt_path="~/scratch/hf/stanford-star/rt-plurel/classification",
        db_task_list="expts/pretrain/all_5gb_cutoff.json",
        train_splits=["train"],
        pre_dir="~/scratch/hf/stanford-star/the-join-lite-preprocessed",
        tokens_per_gpu=tokens_per_gpu,
        num_workers=num_workers,
        prefetch_factor=2,
        ctx_size_list=[512, 1024, 2048, 4096, 8192],
        local_ctx_size_list=[256, 512, 1024, 2048, 4096, 8192],
        bfs_width_list=[8, 16, 32, 64, 128, 256],
        prefer_latest_list=[False, True],
        num_walks=10_000,
        walk_length=20,
        mask_prob_max=0.5,
        items_per_task=100_000,
        delta_finetune=True,
        optimizer="muon",
        lr=5e-4,
        wd=0.1,
        lr_warmup_steps=2_000,
        lr_decay_steps=0,
        grad_norm_max=1.0,
        total_bs=1024,
        total_steps=100_001,
        early_stop_after_steps=None,
        can_select_init_model=False,
        swa_momentum=0.9995,
        seed=0,
        mmap_populate=True,
        timeout_per_item=10.0,
        eval_freq=1_000,
        keep_all_ckpts=True,
        vector_db_path=None,
        db_cutoff=None,
        resume_save_mins=20.0,
        eval_splits=["val"],
        eval_db_task_list="expts/pretrain/eval-tasks.json",
        eval_pre_dir="~/scratch/hf/stanford-star/relbench-preprocessed",
        eval_tokens_per_gpu=tokens_per_gpu,
        eval_num_workers=num_workers,
        eval_prefetch_factor=2,
        eval_num_walks=10_000,
        eval_walk_length=20,
        eval_items_per_task=1024,
        eval_ctx_size_list=[8192],
        eval_mmap_populate=True,
        eval_shuffle_seed=0,
        eval_context_seed=0,
        eval_ensemble_size=1,
        eval_vector_db_path=None,
        eval_lcs_bw_pl_grid=[(256, 32, True)],
        targets={},
        project="2026-08-07-pretrain",
        entity="rtv2",
        run_name="new-pretrain",
        wandb_disabled=False,
        out_root="~/scratch/relational-transformer/pretrain",
    ),
    resources=resources,
    name="pretrain",
    run_id=None,
    repo_root=str(Path(__file__).resolve().parents[2]),
    cluster=marlowe.MARLOWE,
    job_env="expts/job_env.sh",
    log_root="~/scratch/relational-transformer/pretrain/slurm-logs",
    clone_root="~/roach_clones",
    secrets_dir="~/scratch/.secrets",
)
